name: animated_stack_widget
description: A Stack widget which supports animated addition/removal of children.
version: 0.0.1
homepage: https://github.com/rorystephenson/animated_stack

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
